"""The analytic fixture: a synthetic stereo pair with closed-form ground truth.

FAITHFUL PORT of ``make_synthetic_scene`` from
``visgraf/bioeye@e908170:active_stereo_demo.py:47-77``. Numerically unchanged.

This is a **test fixture, not a scene family** (CLAUDE.md; foreclosure fc-004).
It exists so tests are fast and exact. A finding that rests on it has misused it,
and there is a specific reason recorded in ``docs/inherited-measurements.yaml``
as ``gap-010``: the right image is synthesised by inverse-warping the left with
``mode="reflect"``, so the fixture has **no true half-occlusions**. Any occlusion
claim measured here is unsound.
"""

from __future__ import annotations

from typing import TypedDict

import numpy as np
from numpy.typing import NDArray
from scipy.ndimage import gaussian_filter, map_coordinates

FloatArray = NDArray[np.float32]


class CameraParams(TypedDict):
    """Rectified parallel rig. Pixels and metres; the predecessor's contract."""

    f_px: float
    baseline: float
    H: int
    W: int


def make_synthetic_scene(
    H: int = 240,
    W: int = 320,
    f_px: float = 700.0,
    baseline: float = 0.065,
    seed: int = 0,
) -> tuple[FloatArray, FloatArray, FloatArray, CameraParams]:
    """A few fronto-parallel 'cards' at different depths on a far background.

    Returns left, right (float [0,1]), depth_gt (metres), and camera params.
    Right is generated by inverse-warping left with the ground-truth disparity,
    so a correct matcher recovers ``d_gt = f*I/Z``.

    Deterministic in ``seed`` via an explicit ``default_rng``; no global NumPy
    state is touched.
    """
    rng = np.random.default_rng(seed)

    # Depth map (metres): background + three cards nearer the camera. Depths are
    # kept moderate so occlusion bands (~disparity difference in px) stay thin
    # relative to the card sizes, keeping the correspondence problem tractable.
    Z = np.full((H, W), 4.5)
    Z[40:170, 40:170] = 3.0
    Z[120:220, 160:290] = 2.4
    Z[30:100, 205:290] = 3.6
    Z = gaussian_filter(Z, 0.6)  # soften edges slightly

    d_gt = f_px * baseline / Z  # ground-truth disparity (px), all positive

    # Random but spatially-structured texture so block matching has signal.
    tex = rng.standard_normal((H, W))
    tex = gaussian_filter(tex, 1.0)
    tex = (tex - tex.min()) / (np.ptp(tex) + 1e-9)
    left = tex

    # right[y,x] = left[y, x + d]  (near points shift left in the right image)
    #
    # mode="reflect" is the fixture's defining limitation, not a detail: where a
    # nearer card should hide background, the sampler reflects LEFT texture back
    # instead of showing a different surface. See gap-010.
    ys, xs = np.mgrid[0:H, 0:W].astype(np.float64)
    right = map_coordinates(left, [ys, xs + d_gt], order=1, mode="reflect")

    params: CameraParams = {
        "f_px": float(f_px),
        "baseline": float(baseline),
        "H": H,
        "W": W,
    }
    return (
        left.astype(np.float32),
        right.astype(np.float32),
        Z.astype(np.float32),
        params,
    )


def true_disparity(depth_gt: FloatArray, params: CameraParams) -> FloatArray:
    """Ground-truth disparity in px, ``d = f*I/Z``.

    MEASUREMENT ONLY. Nothing in the loop may call this — see ``loop.py``.
    """
    d: FloatArray = (params["f_px"] * params["baseline"] / depth_gt).astype(np.float32)
    return d
